# Generated by Django 4.1.7 on 2023-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Quantity', models.IntegerField(blank=True, null=True)),
                ('Product_Price', models.IntegerField(blank=True, null=True)),
                ('Product_descrption', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Image', models.ImageField(upload_to='Product')),
            ],
        ),
    ]
