# Generated by Django 4.1.7 on 2023-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('passw', models.CharField(blank=True, max_length=100, null=True)),
                ('con_passw', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
